version: "3.7"
name: ryd-challenge

services:
  database:
    container_name: postgres-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    image: postgres:13
    # Remove or rename this line to avoid conflicts
    # container_name: postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data:/var/lib/postgresql/data

  adminer-db:
    image: adminer
    container_name: adminer-db
    ports:
      - "${ADMINER_PORT}:8080"
    depends_on:
      - database
    environment:
      ADMINER_DEFAULT_SERVER: database
      ADMINER_DEFAULT_USERNAME: ${POSTGRES_USER}
      ADMINER_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
      ADMINER_DEFAULT_DATABASE: ${POSTGRES_DB}